language: node_js
node_js:
  - 12
script: yarn install && eleventy --pathprefix="/geld-en-zo/"
deploy:
  local-dir: _site
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: main
